site_name: Yuyang WANG
nav:
    - Home: index1.md
    - Bio: bio1.md
    - Research: research1.md
    - Publications: publications.md
    - Teaching: teaching1.md
    - Services: service1.md
    - Team: team1.md
#    - About: about.md



# 主题切换的方法：
# （1） conda install -c conda-forge mkdocs-bootswatch
# （2） 进入：https://mkdocs.github.io/mkdocs-bootswatch/#flatly， 查看可以使用的主题
theme:
    name: flatly
